FROM python:3.12-slim

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY . .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "ai_service.py"]